### ISSUE TITLE
No extension after recreate container

### ISSUE THREAD

**Issue by Sim7b** [crazy-max/docker-flarum#10]
#### Steps to reproduce this issue

1. Recreate Container

> Extension should be still active

#### Actual behaviour

> No more active extension but when I reinstall them, conf is still here.

**Comment by Sim7b** [comment]
Maybe a cache problem ?

**Comment by crazy-max** [comment]
Hi @Sim7b, I need more info. Please create a proper [bug report](https://github.com/crazy-max/docker-flarum/issues/new?template=bug_report.md) (with all stipulated info).
