### ISSUE TITLE
How can I add an SSL certificate to realize the access to HTTPS

### ISSUE THREAD

**Issue by qingfengfenga** [crazy-max/docker-flarum#19]
How can I add an SSL certificate to achieve HTTPS access, neither the dockerfile nor the initialization script in the container can be found nginx.conf Configuration.

**Comment by crazy-max** [comment]
@qingfengfenga There is a [basic example available](https://github.com/crazy-max/docker-flarum/tree/master/examples/traefik) to use this image with Traefik as reverse proxy with auto SSL through Let's Encrypt.
