### ISSUE TITLE
Only Flarum docker that works but how to install a plugin

### ISSUE THREAD

**Issue by czco** [crazy-max/docker-flarum#2]
I wish to post a video but its so hard. googling shows https://discuss.flarum.org/d/647-s9e-mediaembed-embed-videos-and-third-party-content would be ideal but how to install it when using this docker

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-flarum#manage-extensions

**Comment by czco** [comment]
`ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml`

@crazy-max the method you suggested requires me to have docker-compose.yml somewhere and be in that directory however I started this docker using `docker run -p ...`
