### ISSUE TITLE
Update config.php

### ISSUE THREAD

**Issue by wonderbeel** [crazy-max/docker-flarum#39]
With the release of flarum 1.0 there have been some changes to the config.php file (for example now there is an [headers section](https://discuss.flarum.org/d/27903-why-is-there-no-referer-in-request-headers/8)) but the script generating it is still using the beta version of that file
https://github.com/crazy-max/docker-flarum/blob/48c422c61fab7a5941d009d07eee111ee76b7924/rootfs/etc/cont-init.d/03-config.sh#L166
It seems that the `headers` section is the only new one that is missing, if I find something else I will try to report it ASAP.

**Comment by crazy-max** [comment]
@wonderbeel Thanks for your feedback, env vars have been added in the latest release. See https://github.com/crazy-max/docker-flarum/commit/ab64a39e8b020a168accc89643cf7fb70e97aba3
