### ISSUE TITLE
cors issue

### ISSUE THREAD

**Issue by karimmahrouskamil** [crazy-max/docker-flarum#41]
### Behaviour
after launching **the docker-compose in examples/compose** it gives 

`Access to font at 'http://127.0.0.1:8000/assets/fonts/fa-solid-900.woff' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by crazy-max** [comment]
@karimmahrouskamil From a CORS standpoint `http://127.0.0.1:8000` and `http://localhost:8000` are different domains. If you don't really care you can set `FLARUM_REFERRER_POLICY=*`.
