### ISSUE TITLE
unsafe and danger re-install (03-config.sh)

### ISSUE THREAD

**Issue by nthypes** [crazy-max/docker-flarum#48]
https://github.com/crazy-max/docker-flarum/blob/9c206ff0509c31669623c305f997d635edc891fb/rootfs/etc/cont-init.d/03-config.sh#L139

At the start/config script, reinstall occurs if the file `/data/assets/rev-manifest.json` not exits, but this is extremaly unsafe, since this file can be removed in an extension removal (as you can see in this [post](https://discuss.flarum.org/d/12529-can-i-remove-an-extention-on-flarum))

Also, accordingly to Flarum [docs](https://docs.flarum.org/config), the file that should be consider to decide if we have or not a runnign installation in the container is the `config.php`.

```If the file exists, it tells Flarum that it has already been installed. It also provides Flarum with database info and more.```

**Comment by nthypes** [comment]
I think that the most safe way is to check if Flarum is already installed looking at the database.

I recommend running the following script, before the image script:

`# Check if migration table exists
DB_PREFIX=${DB_PREFIX:-flarum_}
MIGRATION_IS_EMPTY="SELECT 1 FROM ${DB_PREFIX}_migrations LIMIT 1"

if [[ $(mysql -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD} -P ${DB_PORT} -e "$MIGRATION_IS_EMPTY" ${DB_NAME}) ]]
then
    echo "Migration table exists and is not empty..."
    yasu flarum:flarum touch /data/assets/rev-manifest.json
else
    echo "First install. Migration table was not found or was empty..."
    rm -rf /data/assets/rev-manifest.json
fi`

**Comment by fatihusta** [comment]
> 
I agree with you but your code has a bug.
This query return empty when started very first time. So "shell" returns an error.
```
if [ $(mysql -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD} -P ${DB_PORT} -sse "$MIGRATION_IS_EMPTY" ${DB_NAME}) -gt 0 ]; then
```

I think, we don't need to count migration table. Just having a migration table is enough.
