### ISSUE TITLE
Flarum custom installed extensions missing after update

### ISSUE THREAD

**Issue by DrifterOne** [crazy-max/docker-flarum#85]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-flarum/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

A docker update will work but custom installed extensions will be missing afterwards.
Could you please add a persistant storage for extensions not bundled and added after installation?
Also an option to modify the docker compose file would work, but it has to be persistent either

### Expected behaviour

expected is that after adding a custom extension it will still persist after performing a container update

### Actual behaviour

container update will wipe all custom installed extensions

### Steps to reproduce

install custom extension or language
update container
it'll be missing

### Docker info

```text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.17.3)

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 20.10.21
 Storage Driver: btrfs
  Build Version: Btrfs v5.10.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d1
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.19.17-Unraid
 Operating System: Slackware 15.0 x86_64 (post 15.0 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.7GiB
 Name: store1
 ID: DEOO:ROO3:EEH7:N7ZN:KR3P:D3F4:EO75:74ML:X2DN:UPC5:ARBI:CM57
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Logs

```text
none
```

**Comment by crazy-max** [comment]
Can't help without command invoked and/or compose file

**Comment by DrifterOne** [comment]
Could you please add the following extension to the compose file? These would generally make sense:

composer require fof/sitemap
composer require v17development/flarum-seo
composer require flarum-lang/german

Thank you

**Comment by crazy-max** [comment]
> Could you please add the following extension to the compose file? These would generally make sense:

Don't want to ship non-vanilla Flarum with exntesions. This is the user who decides what to add as extension.
